added draft of accumulating gradients and some documentation
BMIRDS/WSI-PLP pull request #5
Opened 2023-07-31 03:11 UTC by adas2125

I modified the `train` function in `trainer/fitter.py` so that it would accumulate gradients. I also added the necessary changes in the `configs/config_ibd_train.py` file. If the `accumulation_steps` is not provided in the configs file, then the function should work as before. However, I am not sure if this function is working properly, since I did not see many differences in the results of training.

2023-09-24 04:09 UTC, adas2125 commented
Added modifications to `utils/prepare_visualization.py` script and transferred create_attention_maps script from notebook to a python script.

2024-01-06 21:49 UTC, ntomita requested changes
Thanks for PR. Many improvements found but also found consistency and minor issues. Please see my comments

2024-01-06 21:49 UTC, ntomita commented on maskhit/configs/config_default_visualization.yml
Please add comments to explain the parameters and how it should be utilized.

2024-01-06 21:49 UTC, ntomita commented on maskhit/create_attention_maps.py
1. Please sort the import section. it should have three blocks: python standard libraries, 3rd party libraries (cv2, numpy, matlab, openslide etc), then own libraries like utils.- and vis.-.
2. For each function, please add type hints for parameters.
3. Please add doc to explain what this script/module about, immediately after the import section.
4. Some lines have long chars (> 79). Please format them nicely for better readability.

2024-01-06 21:49 UTC, ntomita commented on maskhit/hard_grid.py
This is hardcoded for ibd dataset. It could be still useful but the file name is misleading. How about rename it and put it in a directory:
`git mv hard_grid.py utils/hard_grid_ibd.py`

2024-01-06 21:49 UTC, ntomita commented on maskhit/model/archs/vit/deepvit.py
I am not sure about this module. Is this for visualization?
Function at 35, it's great you unfold the operation. But maybe better suppress printing if you are done debugging it, or elaborate the printing if the values are helpful as INFO. Could empty case happen? Maybe better raise error if that's not expected.

2024-01-06 21:49 UTC, ntomita commented on maskhit/options/train_options.py
Please be careful when you modify the default values. **It's okay to change if that's generally helpful for others**. Could you add the reasoning in each help section for the change?

Also please pay extra attention to boolean parameters with `action='store_true'`. If you change the default to True, then you have to change action to false and change the argument name too. I see some changes are conceptually wrong. For example, if you default to True for weighted_loss, then it should be 'store_false' and '--no-weighted-loss'. and you have to flip it to make it consistent with the rest of the code (`weighted_loss = not args.no_weighted_loss`).

Overall, please review if the changes worth the cost. If the changes are mainly for your dataset, use a bash script to simplify a command (and that's helpful for record purpose).

2024-01-06 21:49 UTC, ntomita commented on maskhit/quick_test.py
Please add docstring. Please use pathlib instead of os library.

2024-01-06 21:49 UTC, ntomita commented on maskhit/train.py
> +
Please sort the imports.

2024-01-06 21:49 UTC, ntomita commented on maskhit/train.py
>          help="Path to the user-defined configuration file.")
What's aggregated predictions?
Also why it's in train.py script?

2024-01-06 21:49 UTC, ntomita commented on maskhit/train.py
> +        args.wd_attn = args.wd_fuse = args.wd_pred = args.wd_loss = config.patch.wd
Please avoid bulk assignment for better readability.

2024-01-06 21:49 UTC, ntomita commented on maskhit/train.py
Overall this script is very messy and unstructured so once I merge your PR I will do some refactoring.

2024-01-06 21:49 UTC, ntomita commented on maskhit/train.py
>  os.chdir(os.path.dirname(os.path.abspath(__file__)))
Let's use pathlib

2024-01-06 21:49 UTC, ntomita commented on maskhit/train.py
> +        split_value = value_to_split.split('.')[0]
Could you double check if line 259 is generalizable? Thanks.

2024-01-06 21:49 UTC, ntomita commented on maskhit/train.py
> +    except:
When you use `except`, make sure add target error types such as ValueError. Without that (and comments), it's not clear which case you are taking care of.

2024-01-06 21:49 UTC, ntomita commented on maskhit/trainer/fitter.py
> +        print(pickle_file.keys())
Is this print statement for debugging purpose? In general, it's okay to print values if that's helpful, but make sure you elaborate that; otherwise users have no idea what's just printed.

2024-01-06 21:49 UTC, ntomita commented on maskhit/trainer/fitter.py
> +                label_classes = self.config.dataset.classes.split(',')
I was wondering what is this and figured that the value in `config_ibd_train.yaml`.
When you add any logic in any main code, that option should be available to other datasets, even if others may not immediately utilize it. In this case, the extra parameters you added in the config should be propagated to the `config_default.yaml`; otherwise others won't tell what's available. Please double check if you have any other such config parameters.

2024-01-06 21:49 UTC, ntomita commented on maskhit/trainer/fitter.py
>              os.makedirs(os.path.dirname(pred_file), exist_ok=True)
Please use pathlib.

2024-01-06 21:49 UTC, ntomita commented on maskhit/trainer/fitter.py
> +            performance_measure = torch.tensor(val_res['f1']) # changed from 'auc' to 'f1-score'
This choice could be decided in config file.

2024-01-06 21:49 UTC, ntomita commented on maskhit/trainer/fitter.py
> +        epoch_start_monitoring = 5 # changed from 0 to 5
Why this change?

2024-01-06 21:49 UTC, ntomita commented on maskhit/trainer/metrics.py
> +    base_path = 'predictions/ibd_project/2023_5_30_new-test-'
Please avoid writing such hardcoded code.

2024-01-06 21:49 UTC, ntomita commented on maskhit/trainer/metrics.py
> +def read_and_adjust_csv(file_name, last_max_id):
Please add docstring and typehint.
Also in docstring, concisely describe the expected csv data format. (This is important when you have some assumption on which column should have what kind of data.)

2024-01-06 21:49 UTC, ntomita commented on maskhit/trainer/metrics.py
> +def calculate_metrics(ids, preds, targets, outcome_type='survival', label_classes = ['Inactive', 'Mild', 'Moderate', 'Severe'], mode = ''):
Again, please avoid such ad-hoc approach. If necessary to pass label_classes, please utilize config values.

2024-01-06 21:49 UTC, ntomita commented on maskhit/trainer/metrics.py
> +        df = pd.DataFrame(np.concatenate([ids, targets, softmax(preds, axis=1)], axis=1))
Could you add comments to each code around here. It's always better to be explicit.

2024-01-06 21:49 UTC, ntomita commented on maskhit/trainer/metrics.py
> +def save_multi_class_auc(probs, targets, label_classes, save_path):
Please add docstring and typestring for any new functions.
`save_path` not utilized?

2024-01-06 21:49 UTC, ntomita commented on maskhit/trainer/metrics.py
> +    def evaluate(self, mode = ''):
Is it safe to leave `mode` empty string? Just asking based on my instinct.

2024-01-06 21:49 UTC, ntomita commented on maskhit/utils/find_best_cases.py
> +    parser.add_argument('--file', default='predictions/ibd_project/2023_5_30_new-test-0-predictions.csv',
Please avoid such hard-coded default values.

2024-01-06 21:49 UTC, ntomita commented on maskhit/utils/get_region_info.py
> +        f"data/IBD_PROJECT/{row['id_svs']}/mag_{magnification}-size_{patch_size}/meta.pickle"
Please avoid hard-coded values.

2024-01-06 21:49 UTC, ntomita commented on maskhit/utils/get_region_info.py
> +                    default=20,
Please add docstring to explain what's this script about.
Why changing default values? See my previous comments about default value.

2024-01-06 21:49 UTC, ntomita commented on maskhit/utils/prepare_visualization_data.py
> +region_size = 2240
Please reconsider this hard-coded approach. It was BRCA and now IBD, both approaches are not appropriate.

2024-01-06 21:49 UTC, ntomita commented on maskhit/utils/prepare_visualization_data.py
Overall this script's quality seems not okay for PR.

2024-01-06 21:49 UTC, ntomita commented on maskhit/utils/random_grid_search.py
> +    df = pd.read_csv('logs/ibd_project/2023_5_30-test-0_data.csv')
Avoid hard-coded.

2024-01-06 21:49 UTC, ntomita commented on maskhit/utils/random_grid_search.py
> +    temp_file_path = os.path.join("temp", f"config_temp_{lr_pred}_{wd_pred}_{dropout}_{accum_steps}_{batch_size}.yml")
Please use pathlib.

2024-01-07 05:30 UTC, adas2125 commented on maskhit/trainer/fitter.py
> +        epoch_start_monitoring = 5 # changed from 0 to 5
I made this change so the model would train for at least 5 epochs before checking for early stopping. However, I have changed this back to 0.

2024-01-08 02:40 UTC, 11tonystark commented on maskhit/train.py
>          help="Path to the user-defined configuration file.")
"Aggregated predictions function" consolidates the predictive outcomes, such as confusion matrices and AUC,   across five distinct  folds. By combining the results from each fold, this function provides a comprehensive overview of the model's performance over the entire dataset.
Added  a separate utility script under utils folders to handle aggregated predictions for the overall structure and readability of your codebase

2024-01-08 02:45 UTC, adas2125 commented on maskhit/train.py
> +        split_value = value_to_split.split('.')[0]
It assumes that the case_number still has an extension like .svs

2024-01-08 03:00 UTC, 11tonystark commented on maskhit/trainer/fitter.py
> +            performance_measure = torch.tensor(val_res['f1']) # changed from 'auc' to 'f1-score'
added in config file

2024-01-09 18:24 UTC, adas2125 commented on maskhit/trainer/metrics.py
> +    def evaluate(self, mode = ''):
I think it is safe as `mode` is being passed into only the calculate metrics function.

2024-01-15 22:28 UTC, ntomita requested changes
I have minor comments. Please address them, thanks!

2024-01-15 22:28 UTC, ntomita commented on maskhit/options/train_options.py
>                                   help='number of svs sampled in sample-patient mode')
The help message seems not accurate (num regions or svs?) or maybe I don't understand well. When _sample-patient_ is False, then this parameter is ignored or still used as the number of regions to be sampled?

2024-01-15 22:28 UTC, ntomita commented on maskhit/options/train_options.py
> +                                 default=True,
This must be False by default if you use store_true for action.

2024-01-15 22:28 UTC, ntomita commented on maskhit/options/train_options.py
> +                                 default=True, # changed from False to True
This should be False again.

2024-01-15 22:28 UTC, ntomita commented on maskhit/options/train_options.py
> +                                 default=200, # changed from 5 to 200
This default value is technically not activated as > epochs.

2024-01-15 22:28 UTC, ntomita commented on maskhit/options/train_options.py
> +                                 default=0, # changed from 1e-3 (we can try 2.5e-3 to get to know if model is able to learn)
Why 0? I am not sure about the reason of this change.

2024-01-15 22:28 UTC, ntomita commented on maskhit/options/train_options.py
> +                                 default=0, # changed from 1e-3 (we can try 2.5e-3 to get to know if model is able to learn)
Ah, is this for testing? If so why you need lr for testing in the first place?

2024-01-15 22:28 UTC, ntomita commented on maskhit/options/train_options.py
> +                                 default=0,
What's the prediction model?

2024-01-15 22:28 UTC, ntomita commented on maskhit/options/train_options.py
> +                                 default=True,
need fix

2024-01-15 22:28 UTC, ntomita commented on maskhit/options/train_options.py
> +                                 default='2023_5_30-0', # FIX: changed from pretrained_20x_448_resnet34
need fix

2024-01-15 22:28 UTC, ntomita commented on maskhit/options/train_options.py
>                                   help='proportion for masking tokens, masked:original:random')
Requesting documentation for this.

2024-01-15 22:28 UTC, ntomita commented on maskhit/quick_test.py
> +        org_cmd = org_cmd.replace("--timestr=2023_5_30_new", "")
should avoid hard-coded

2024-01-15 22:28 UTC, ntomita commented on maskhit/trainer/metrics.py
> +        preds = df.groupby(0).apply(lambda x: find_confident_instance(x.to_numpy()[:, 2:]))
The original algorithm seems also valid. Can a user choose which one to use?

2024-01-15 22:28 UTC, ntomita commented on maskhit/trainer/metrics.py
> +                    if mode == 'test' or mode == 'val':
FYI you can write: 
`mode in ['test', 'val']`

2024-01-15 22:28 UTC, ntomita commented on maskhit/utils/prepare_visualization_data.py
> +df_meta = df_meta.loc[df_meta.case_number.apply(lambda entry: entry.split('.')[0]).isin(df_svs.id_svs)]
This line is too long. how about like this:
```
fn_extract_prefix = lambda x: x.split('.')[0])
ids_selected = df_meta.case_number.apply(fn_extract_prefix)
df_meta = df_meta.loc[ids_selected.isin(df_svs.id_svs)]
```

2024-01-15 22:28 UTC, ntomita commented on maskhit/utils/prepare_visualization_data.py
> +df_meta.merge(df_locs[['case_number','svs_path','id_svs']].drop_duplicates('id_svs'), on='case_number')
Is it safe to assume the input always has case_number instead of id_patient?

2024-01-19 03:37 UTC, adas2125 commented on maskhit/options/train_options.py
> +                                 default=True,
We defined the `weighted_loss` in the config file and removed it from `train_options.py`

2024-01-19 03:38 UTC, adas2125 commented on maskhit/options/train_options.py
> +                                 default=200, # changed from 5 to 200
we kept the default value to 5

2024-01-19 03:39 UTC, adas2125 commented on maskhit/options/train_options.py
> +                                 default=0, # changed from 1e-3 (we can try 2.5e-3 to get to know if model is able to learn)
We removed `lr-pred` from `train_options.py` and added to the config file.

2024-01-19 03:44 UTC, adas2125 commented on maskhit/options/train_options.py
> +                                 default='2023_5_30-0', # FIX: changed from pretrained_20x_448_resnet34
We have this in our config file, so we removed from `train_options.py`

2024-01-19 04:00 UTC, adas2125 commented on maskhit/options/train_options.py
>                                   help='proportion for masking tokens, masked:original:random')
added documentation to the `train_options.py` file file

2024-01-19 04:12 UTC, adas2125 commented on maskhit/utils/prepare_visualization_data.py
> +df_meta.merge(df_locs[['case_number','svs_path','id_svs']].drop_duplicates('id_svs'), on='case_number')
It likely depends on the dataset definition in the preprocessing scripts. We adjusted the file to try both just in case id_patient is not in the pickle file. In our case, id_patient was not present

2024-01-19 04:17 UTC, adas2125 commented on maskhit/trainer/metrics.py
> +        preds = df.groupby(0).apply(lambda x: find_confident_instance(x.to_numpy()[:, 2:]))
The find average instance function has not been implemented yet. I think this refers to the patients. Since for the IBD project, we are looking at individual WSIs, this does not really apply to us. We can keep it as most confident prediction for now, but Shuai had said that average prediction may perform better.

2024-01-19 04:36 UTC, adas2125 commented on maskhit/options/train_options.py
> +                                 default=0,
We are not sure. This could relate to the FinalPred class present in `model/models.py`

2024-01-19 04:38 UTC, adas2125 commented on maskhit/options/train_options.py
> +                                 default=True,
When we change this back to False, we get the following error:
`Missing key(s) in state_dict:`

2024-01-19 04:42 UTC, adas2125 commented on maskhit/options/train_options.py
>                                   help='number of svs sampled in sample-patient mode')
Yes, this should be regions of svs. In the `train.py` script, we see `args.mode_ops['train'][
    'regions_per_patient'] = config.model.regions_per_svs * args.svs_per_patient`. This parameter was also moved to the config file.

2024-01-19 19:51 UTC, merged